#!/bin/bash
#========================================================================
# file to be INCLUDED ONLY as it only defines functions

function funcs() {

    [[ $1 == "--help" || $1 == "-h" || $1 == "help" ]] && printf " 
This bash function() is used to list/display functions 

Usage:
	funcs
		list all the defined bash functions
	funcs <function name>
		displays the function onctent for the named function 

" && return
	if [[ $1 == "" ]] ; then

		# if no params provided then list all functions which
		# do not start with an underscore
		declare -F | awk '{print $3}' | grep --color=auto -v "^_"

	else

		# show the contenst of the named function
		declare -f $@ 
		# declare -f $@ | awk '{ printf("%5d  %s\n",NR,$0) }'

	fi

}


